<html>
<head>
    <title>Index</title>
</head>
<body>
    <h1>MVC DZ</h1>
    <div class="content">
        <a href="https://github.com/pusachev/php/raw/master/images/sparrow.jpeg" >
            <img src="https://github.com/pusachev/php/raw/master/images/sparrow.jpeg" ></a>
        <div>
            <p>"Все видели как я это сделал? Ибо я отказываюсь это повторять"</p>
        </div>
    </div>
</body>
</html>

